//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kharban_AdminAPI
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Kharban {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Kharban() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kharban_AdminAPI.Resource_Kharban", typeof(Resource_Kharban).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is closed/deleted. Please contact Administrator, if you have closed account accidentally..
        /// </summary>
        public static string AccountClosed {
            get {
                return ResourceManager.GetString("AccountClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is deactivated. Please contact Administrator, to active your account..
        /// </summary>
        public static string AccountDeactivated {
            get {
                return ResourceManager.GetString("AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation mail of Dil Ke Risthe.
        /// </summary>
        public static string ActivationMailOfDilKeRisthe {
            get {
                return ResourceManager.GetString("ActivationMailOfDilKeRisthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !!!.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to block this member?.
        /// </summary>
        public static string AreYouSureToBlockThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToBlockThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel invitation?.
        /// </summary>
        public static string AreYouSureToCancelInvitation {
            get {
                return ResourceManager.GetString("AreYouSureToCancelInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to ignore this member..
        /// </summary>
        public static string AreYouSureToIgnoreThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToIgnoreThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to recall user?.
        /// </summary>
        public static string AreYouSureToRecallUser {
            get {
                return ResourceManager.GetString("AreYouSureToRecallUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Remind Invitation..
        /// </summary>
        public static string AreYouSureToRemindInvitation {
            get {
                return ResourceManager.GetString("AreYouSureToRemindInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove from Short List?.
        /// </summary>
        public static string AreYouSureToRemoveFromShortList {
            get {
                return ResourceManager.GetString("AreYouSureToRemoveFromShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove user from ignore list?.
        /// </summary>
        public static string AreYouSureToRemoveUserFromIgnoreList {
            get {
                return ResourceManager.GetString("AreYouSureToRemoveUserFromIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to report abuse this member?.
        /// </summary>
        public static string AreYouSureToReportAbuseThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToReportAbuseThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to send invitation this member..
        /// </summary>
        public static string AreYouSureToSendInvitationThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToSendInvitationThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to shortlist this member.
        /// </summary>
        public static string AreYouSureToShortlistThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToShortlistThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to unblock user?.
        /// </summary>
        public static string AreYouSureToUnblockUser {
            get {
                return ResourceManager.GetString("AreYouSureToUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Successfully.
        /// </summary>
        public static string BlockedSuccessfully {
            get {
                return ResourceManager.GetString("BlockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not able to access your account. Please contact system administrator..
        /// </summary>
        public static string ContactSystemAdministrator {
            get {
                return ResourceManager.GetString("ContactSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully..
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Accept Invitation. Please Try Again.
        /// </summary>
        public static string FailedToAcceptInvitationPleaseTryAgain {
            get {
                return ResourceManager.GetString("FailedToAcceptInvitationPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Successfully..
        /// </summary>
        public static string IgnoreSuccessfully {
            get {
                return ResourceManager.GetString("IgnoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string InsertSuccessfully {
            get {
                return ResourceManager.GetString("InsertSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Partner Id..
        /// </summary>
        public static string InvalidPartnerID {
            get {
                return ResourceManager.GetString("InvalidPartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Accepted.
        /// </summary>
        public static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Removed Successfully.
        /// </summary>
        public static string InvitationRemovedSuccessfully {
            get {
                return ResourceManager.GetString("InvitationRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Sent Successfully..
        /// </summary>
        public static string InvitationSentSuccessfully {
            get {
                return ResourceManager.GetString("InvitationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will Upload Id Later.
        /// </summary>
        public static string IWillUploadIdLater {
            get {
                return ResourceManager.GetString("IWillUploadIdLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This entered email has already exist..
        /// </summary>
        public static string MailAlreadyExist {
            get {
                return ResourceManager.GetString("MailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is not verified. If you haven&apos;t received verification email. please resend it..
        /// </summary>
        public static string MailNotVerified {
            get {
                return ResourceManager.GetString("MailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sucessfully Sent..
        /// </summary>
        public static string MailSucessfullySent {
            get {
                return ResourceManager.GetString("MailSucessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Has Re-call..
        /// </summary>
        public static string MemberHasRecall {
            get {
                return ResourceManager.GetString("MemberHasRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No List Found..
        /// </summary>
        public static string NoListFound {
            get {
                return ResourceManager.GetString("NoListFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Remove. Please Try Again..
        /// </summary>
        public static string NotRemovePleaseTryAgain {
            get {
                return ResourceManager.GetString("NotRemovePleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Visible To All..
        /// </summary>
        public static string NotVisibleToAll {
            get {
                return ResourceManager.GetString("NotVisibleToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!!!.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Deleted Successfully..
        /// </summary>
        public static string PhotoDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PhotoDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Uploaded Successfully..
        /// </summary>
        public static string PhotoUploadedSuccessfully {
            get {
                return ResourceManager.GetString("PhotoUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Added Successfully..
        /// </summary>
        public static string PlanAddedSuccessfully {
            get {
                return ResourceManager.GetString("PlanAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct OTP..
        /// </summary>
        public static string PleaseEnterCorrectOTP {
            get {
                return ResourceManager.GetString("PleaseEnterCorrectOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter OTP..
        /// </summary>
        public static string PleaseEnterOTP {
            get {
                return ResourceManager.GetString("PleaseEnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string PleaseEnterYourEmailAddress {
            get {
                return ResourceManager.GetString("PleaseEnterYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again Later..
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your password..
        /// </summary>
        public static string PleaseTypeYourPassword {
            get {
                return ResourceManager.GetString("PleaseTypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least one identity.
        /// </summary>
        public static string PleaseUploadAtLeastOneIdentity {
            get {
                return ResourceManager.GetString("PleaseUploadAtLeastOneIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Profile Photo.
        /// </summary>
        public static string PleaseUploadProfilePhoto {
            get {
                return ResourceManager.GetString("PleaseUploadProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName Has Accepted Your Invitation..
        /// </summary>
        public static string ProfileNameHasAcceptedYourInvitation {
            get {
                return ResourceManager.GetString("ProfileNameHasAcceptedYourInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture Has Updated..
        /// </summary>
        public static string ProfilePictureHasUpdated {
            get {
                return ResourceManager.GetString("ProfilePictureHasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is under screening. It will be activated within 24 working hours..
        /// </summary>
        public static string ProfileUnderScreening {
            get {
                return ResourceManager.GetString("ProfileUnderScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Sent..
        /// </summary>
        public static string ReminderSent {
            get {
                return ResourceManager.GetString("ReminderSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Successfully.
        /// </summary>
        public static string RemoveSuccessfully {
            get {
                return ResourceManager.GetString("RemoveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abused Successfully..
        /// </summary>
        public static string ReportAbusedSuccessfully {
            get {
                return ResourceManager.GetString("ReportAbusedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Requested ProfileName For Data..
        /// </summary>
        public static string RequestedProfileNameForData {
            get {
                return ResourceManager.GetString("RequestedProfileNameForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sent Successfully..
        /// </summary>
        public static string RequestSentSuccessfully {
            get {
                return ResourceManager.GetString("RequestSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type is not there.
        /// </summary>
        public static string RequestTypeIsNotThere {
            get {
                return ResourceManager.GetString("RequestTypeIsNotThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select jpg, jpeg or png file only.
        /// </summary>
        public static string SelectImageValidation {
            get {
                return ResourceManager.GetString("SelectImageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Updated..
        /// </summary>
        public static string SettingUpdated {
            get {
                return ResourceManager.GetString("SettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Shared..
        /// </summary>
        public static string SharedPartnerProfileDetails {
            get {
                return ResourceManager.GetString("SharedPartnerProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortlisted Successfully..
        /// </summary>
        public static string ShortlistedSuccessfully {
            get {
                return ResourceManager.GetString("ShortlistedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong Please Try Again Later..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Invalid request..
        /// </summary>
        public static string SorryInvalidRequest {
            get {
                return ResourceManager.GetString("SorryInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for login..
        /// </summary>
        public static string ThankYouForLogin {
            get {
                return ResourceManager.GetString("ThankYouForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for register with us. An Activation Link Is Sent To Your Email Address For Verified Your Email Address..
        /// </summary>
        public static string ThankYouForRegister {
            get {
                return ResourceManager.GetString("ThankYouForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You For Saving Identity Proof Information!!.
        /// </summary>
        public static string ThankYouForSavingIdentityProofInformation {
            get {
                return ResourceManager.GetString("ThankYouForSavingIdentityProofInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You For Uploading Govt Id !!.
        /// </summary>
        public static string ThankYouForUploadingGovtId {
            get {
                return ResourceManager.GetString("ThankYouForUploadingGovtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You For Verify Your Email Address. Your profile under screening it will be live in 12 working hours..
        /// </summary>
        public static string ThankYouForVerifyYourEmailAddress {
            get {
                return ResourceManager.GetString("ThankYouForVerifyYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address or password entered is invalid..
        /// </summary>
        public static string TheEmailAddressPasswordEnteredInvalid {
            get {
                return ResourceManager.GetString("TheEmailAddressPasswordEnteredInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfully..
        /// </summary>
        public static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Has Requested For Data..
        /// </summary>
        public static string UserNameHasRequestedForData {
            get {
                return ResourceManager.GetString("UserNameHasRequestedForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Has Visited Your Profile..
        /// </summary>
        public static string UserNameHasVisitedYourProfile {
            get {
                return ResourceManager.GetString("UserNameHasVisitedYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Code.
        /// </summary>
        public static string ValidCode {
            get {
                return ResourceManager.GetString("ValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Only On Invitation Send Accecpted..
        /// </summary>
        public static string VisibleOnlyOnInvitationSendAccecpted {
            get {
                return ResourceManager.GetString("VisibleOnlyOnInvitationSendAccecpted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible To Premium Members.
        /// </summary>
        public static string VisibleToPremiumMembers {
            get {
                return ResourceManager.GetString("VisibleToPremiumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Free Member..
        /// </summary>
        public static string YouAlreadyFreeMember {
            get {
                return ResourceManager.GetString("YouAlreadyFreeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Upload More Than 10 Images..
        /// </summary>
        public static string YouCantUploadMoreThan10Images {
            get {
                return ResourceManager.GetString("YouCantUploadMoreThan10Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Accepted Invitation of Username.
        /// </summary>
        public static string YouHaveAcceptedInvitationUserName {
            get {
                return ResourceManager.GetString("YouHaveAcceptedInvitationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already verified your email id..
        /// </summary>
        public static string YouHaveAlreadyVerifiedYourEmailId {
            get {
                return ResourceManager.GetString("YouHaveAlreadyVerifiedYourEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered with us..
        /// </summary>
        public static string YouHaveSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("YouHaveSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upgrade your membership to connect with premium member on  chat &amp; video call..
        /// </summary>
        public static string YouNeedToUpgradeMembership {
            get {
                return ResourceManager.GetString("YouNeedToUpgradeMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is under verification or you can contact our support.
        /// </summary>
        public static string YourAccountUnderVerificationYouCanContactOurSupport {
            get {
                return ResourceManager.GetString("YourAccountUnderVerificationYouCanContactOurSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dil Ke Rishte Profile is Under Screening..
        /// </summary>
        public static string YourDilKeRishteProfileisUnderScreening {
            get {
                return ResourceManager.GetString("YourDilKeRishteProfileisUnderScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Id Is Under Approval..
        /// </summary>
        public static string YourIdIsUnderApproval {
            get {
                return ResourceManager.GetString("YourIdIsUnderApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mobile no is verified successfully..
        /// </summary>
        public static string YourMobileNoIsVerifiedSuccessfully {
            get {
                return ResourceManager.GetString("YourMobileNoIsVerifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has been sent to your mobile no. Please enter it to verify your mobile no..
        /// </summary>
        public static string YourOTPHasBeenSentYourMobileNo {
            get {
                return ResourceManager.GetString("YourOTPHasBeenSentYourMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification identity has been rejected. Please upload your indentity.
        /// </summary>
        public static string YourVerificationIdentityHasBeenRejected {
            get {
                return ResourceManager.GetString("YourVerificationIdentityHasBeenRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would have limited access to your account till your ID is verified by DKR team which may take upto 9 business hours.
        /// </summary>
        public static string YouWouldHaveLimitedAccess {
            get {
                return ResourceManager.GetString("YouWouldHaveLimitedAccess", resourceCulture);
            }
        }
    }
}
