//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kharban_WebAPI
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kharban_WebAPI.Resource_Message", typeof(Resource_Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is closed/deleted. Please contact Administrator, if you have closed account accidentally..
        /// </summary>
        public static string AccountClosed {
            get {
                return ResourceManager.GetString("AccountClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is deactivated. Please contact Administrator, to active your account..
        /// </summary>
        public static string AccountDeactivated {
            get {
                return ResourceManager.GetString("AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation mail of Dil Ke Risthe.
        /// </summary>
        public static string ActivationMailOfDilKeRisthe {
            get {
                return ResourceManager.GetString("ActivationMailOfDilKeRisthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to use this service. You can buy Membership or Addon to avail this service..
        /// </summary>
        public static string AddonNotPurchased {
            get {
                return ResourceManager.GetString("AddonNotPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !!!.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied for business opportunity.
        /// </summary>
        public static string AppliedForBusinessOpportunity {
            get {
                return ResourceManager.GetString("AppliedForBusinessOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to block this Member?.
        /// </summary>
        public static string AreYouSureToBlockThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToBlockThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Cancel Invitation?.
        /// </summary>
        public static string AreYouSureToCancelInvitation {
            get {
                return ResourceManager.GetString("AreYouSureToCancelInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Decline?.
        /// </summary>
        public static string AreYouSureToDecline {
            get {
                return ResourceManager.GetString("AreYouSureToDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to ignore this Member..
        /// </summary>
        public static string AreYouSureToIgnoreThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToIgnoreThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to recall User?.
        /// </summary>
        public static string AreYouSureToRecallUser {
            get {
                return ResourceManager.GetString("AreYouSureToRecallUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remind invitation..
        /// </summary>
        public static string AreYouSureToRemindInvitation {
            get {
                return ResourceManager.GetString("AreYouSureToRemindInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove from Short List?.
        /// </summary>
        public static string AreYouSureToRemoveFromShortList {
            get {
                return ResourceManager.GetString("AreYouSureToRemoveFromShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove user from Ignore List?.
        /// </summary>
        public static string AreYouSureToRemoveUserFromIgnoreList {
            get {
                return ResourceManager.GetString("AreYouSureToRemoveUserFromIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to report Abuse this Member?.
        /// </summary>
        public static string AreYouSureToReportAbuseThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToReportAbuseThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to send invitation this Member..
        /// </summary>
        public static string AreYouSureToSendInvitationThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToSendInvitationThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to shortlist this Member.
        /// </summary>
        public static string AreYouSureToShortlistThisMember {
            get {
                return ResourceManager.GetString("AreYouSureToShortlistThisMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to unblock User?.
        /// </summary>
        public static string AreYouSureToUnblockUser {
            get {
                return ResourceManager.GetString("AreYouSureToUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Successfully.
        /// </summary>
        public static string BlockedSuccessfully {
            get {
                return ResourceManager.GetString("BlockedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Mail From DilKeRishte.com.
        /// </summary>
        public static string ChangePasswordMailSubject {
            get {
                return ResourceManager.GetString("ChangePasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully..
        /// </summary>
        public static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents uploaded for verification!.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have skipped document upload!.
        /// </summary>
        public static string DocumentSkip {
            get {
                return ResourceManager.GetString("DocumentSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already verified..
        /// </summary>
        public static string EmailAddressAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification on DilKeRishte.com.
        /// </summary>
        public static string EmailVerificationMailSubject {
            get {
                return ResourceManager.GetString("EmailVerificationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry acknowledgement from DilKeRishte.
        /// </summary>
        public static string EnquiryAcknowledgementFromDilKeRishte {
            get {
                return ResourceManager.GetString("EnquiryAcknowledgementFromDilKeRishte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry details from DilKeRishte Advertise with us.
        /// </summary>
        public static string EnquiryDetailsFromDilKeRishteAdvertiseWithUs {
            get {
                return ResourceManager.GetString("EnquiryDetailsFromDilKeRishteAdvertiseWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry details from dil ke rishte contact form..
        /// </summary>
        public static string EnquiryDetailsFromDilKeRishteContactForm {
            get {
                return ResourceManager.GetString("EnquiryDetailsFromDilKeRishteContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct password..
        /// </summary>
        public static string EnterCorrectPassword {
            get {
                return ResourceManager.GetString("EnterCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept invitation. Please try again..
        /// </summary>
        public static string FailedToAcceptInvitationPleaseTryAgain {
            get {
                return ResourceManager.GetString("FailedToAcceptInvitationPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is your DilKeRishte account recovery code..
        /// </summary>
        public static string ForgetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email/Phone Number/Profile Id  does not exist. Please try again..
        /// </summary>
        public static string ForgetPasswordNotExist {
            get {
                return ResourceManager.GetString("ForgetPasswordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code has been sent to your registered email address..
        /// </summary>
        public static string ForgetPasswordRequestSent {
            get {
                return ResourceManager.GetString("ForgetPasswordRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code has already sent to your email address..
        /// </summary>
        public static string ForgetPasswordTokenAlreadySent {
            get {
                return ResourceManager.GetString("ForgetPasswordTokenAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have limited access to your account and it will not be visible till you upload your IDs and it will take approximately 9 business hours to verify all your documents by DilKeRishte team..
        /// </summary>
        public static string GovtDocsSkipEmail {
            get {
                return ResourceManager.GetString("GovtDocsSkipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number not found..
        /// </summary>
        public static string GovtIdentityNotFound {
            get {
                return ResourceManager.GetString("GovtIdentityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent to your register mail account..
        /// </summary>
        public static string Hasbeensenttoyourregistermailaccount {
            get {
                return ResourceManager.GetString("Hasbeensenttoyourregistermailaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Successfully..
        /// </summary>
        public static string IgnoreSuccessfully {
            get {
                return ResourceManager.GetString("IgnoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid information..
        /// </summary>
        public static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Partner Id..
        /// </summary>
        public static string InvalidPartnerID {
            get {
                return ResourceManager.GetString("InvalidPartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Accepted.
        /// </summary>
        public static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Removed Successfully.
        /// </summary>
        public static string InvitationRemovedSuccessfully {
            get {
                return ResourceManager.GetString("InvitationRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Sent Successfully..
        /// </summary>
        public static string InvitationSentSuccessfully {
            get {
                return ResourceManager.GetString("InvitationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will upload document(s) later..
        /// </summary>
        public static string IWillUploadIdLater {
            get {
                return ResourceManager.GetString("IWillUploadIdLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your limit for this service is over. You can buy Membership or Addon to avail this service..
        /// </summary>
        public static string LimitOver {
            get {
                return ResourceManager.GetString("LimitOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This entered email has already exist..
        /// </summary>
        public static string MailAlreadyExist {
            get {
                return ResourceManager.GetString("MailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is not verified. If you haven&apos;t received verification email. please resend it..
        /// </summary>
        public static string MailNotVerified {
            get {
                return ResourceManager.GetString("MailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sucessfully Sent..
        /// </summary>
        public static string MailSucessfullySent {
            get {
                return ResourceManager.GetString("MailSucessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member has Re-call..
        /// </summary>
        public static string MemberHasRecall {
            get {
                return ResourceManager.GetString("MemberHasRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for multi location professional video service receive successfully..
        /// </summary>
        public static string MultiLocationProfessionalVideoRequest {
            get {
                return ResourceManager.GetString("MultiLocationProfessionalVideoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No list found..
        /// </summary>
        public static string NoListFound {
            get {
                return ResourceManager.GetString("NoListFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not removed. Please try again..
        /// </summary>
        public static string NotRemovePleaseTryAgain {
            get {
                return ResourceManager.GetString("NotRemovePleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not visible to all..
        /// </summary>
        public static string NotVisibleToAll {
            get {
                return ResourceManager.GetString("NotVisibleToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!!!.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. Please try again later,.
        /// </summary>
        public static string OopsSomethingWentWrong {
            get {
                return ResourceManager.GetString("OopsSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved successfully..
        /// </summary>
        public static string PasswordSavedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Deleted Successfully..
        /// </summary>
        public static string PhotoDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PhotoDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Uploaded Successfully..
        /// </summary>
        public static string PhotoUploadedSuccessfully {
            get {
                return ResourceManager.GetString("PhotoUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Added Successfully..
        /// </summary>
        public static string PlanAddedSuccessfully {
            get {
                return ResourceManager.GetString("PlanAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Membership Plan already avail by you..
        /// </summary>
        public static string PlanExist {
            get {
                return ResourceManager.GetString("PlanExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct security code..
        /// </summary>
        public static string PleaseEnterCorrectCode {
            get {
                return ResourceManager.GetString("PleaseEnterCorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct OTP..
        /// </summary>
        public static string PleaseEnterCorrectOTP {
            get {
                return ResourceManager.GetString("PleaseEnterCorrectOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter OTP..
        /// </summary>
        public static string PleaseEnterOTP {
            get {
                return ResourceManager.GetString("PleaseEnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string PleaseEnterYourEmailAddress {
            get {
                return ResourceManager.GetString("PleaseEnterYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your password..
        /// </summary>
        public static string PleaseTypeYourPassword {
            get {
                return ResourceManager.GetString("PleaseTypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least one identity.
        /// </summary>
        public static string PleaseUploadAtLeastOneIdentity {
            get {
                return ResourceManager.GetString("PleaseUploadAtLeastOneIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Profile Photo.
        /// </summary>
        public static string PleaseUploadProfilePhoto {
            get {
                return ResourceManager.GetString("PleaseUploadProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully post your story.
        /// </summary>
        public static string PostStory {
            get {
                return ResourceManager.GetString("PostStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName has accepted your invitation..
        /// </summary>
        public static string ProfileNameHasAcceptedYourInvitation {
            get {
                return ResourceManager.GetString("ProfileNameHasAcceptedYourInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName has cancelled the invitation..
        /// </summary>
        public static string ProfileNameHasCancelledTheInvitation {
            get {
                return ResourceManager.GetString("ProfileNameHasCancelledTheInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName has declined your invitation..
        /// </summary>
        public static string ProfileNameHasDeclinedYourInvitation {
            get {
                return ResourceManager.GetString("ProfileNameHasDeclinedYourInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture has updated..
        /// </summary>
        public static string ProfilePictureHasUpdated {
            get {
                return ResourceManager.GetString("ProfilePictureHasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is under screening. It will be activated within 24 working hours..
        /// </summary>
        public static string ProfileUnderScreening {
            get {
                return ResourceManager.GetString("ProfileUnderScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Sent..
        /// </summary>
        public static string ReminderSent {
            get {
                return ResourceManager.GetString("ReminderSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Successfully.
        /// </summary>
        public static string RemoveSuccessfully {
            get {
                return ResourceManager.GetString("RemoveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abused Successfully..
        /// </summary>
        public static string ReportAbusedSuccessfully {
            get {
                return ResourceManager.GetString("ReportAbusedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested ProfileName for data..
        /// </summary>
        public static string RequestedProfileNameForData {
            get {
                return ResourceManager.GetString("RequestedProfileNameForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sent Successfully..
        /// </summary>
        public static string RequestSentSuccessfully {
            get {
                return ResourceManager.GetString("RequestSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type is not there.
        /// </summary>
        public static string RequestTypeIsNotThere {
            get {
                return ResourceManager.GetString("RequestTypeIsNotThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your code has been expired..
        /// </summary>
        public static string SecurityCodeExpired {
            get {
                return ResourceManager.GetString("SecurityCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code matched..
        /// </summary>
        public static string SecurityCodeMatched {
            get {
                return ResourceManager.GetString("SecurityCodeMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is not available on your account. You can buy Membership or Addon to avail this service..
        /// </summary>
        public static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Updated..
        /// </summary>
        public static string SettingUpdated {
            get {
                return ResourceManager.GetString("SettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Shared..
        /// </summary>
        public static string SharedPartnerProfileDetails {
            get {
                return ResourceManager.GetString("SharedPartnerProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for sharing information with us..
        /// </summary>
        public static string SharingInformation {
            get {
                return ResourceManager.GetString("SharingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortlisted Successfully..
        /// </summary>
        public static string ShortlistedSuccessfully {
            get {
                return ResourceManager.GetString("ShortlistedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Invalid request..
        /// </summary>
        public static string SorryInvalidRequest {
            get {
                return ResourceManager.GetString("SorryInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to report abuse this member..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully applied promo code..
        /// </summary>
        public static string SuccessfullyAppliedPromoCode {
            get {
                return ResourceManager.GetString("SuccessfullyAppliedPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your suggestion. Your suggestions will help us to improve our services.We will choose best suggestion and honour them with surprise gift..
        /// </summary>
        public static string SuggestionAndWin {
            get {
                return ResourceManager.GetString("SuggestionAndWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise gift from your friend.
        /// </summary>
        public static string SurpriseGiftFromYourFriend {
            get {
                return ResourceManager.GetString("SurpriseGiftFromYourFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for login..
        /// </summary>
        public static string ThankYouForLogin {
            get {
                return ResourceManager.GetString("ThankYouForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing addons..
        /// </summary>
        public static string ThankYouForPurchasingAddons {
            get {
                return ResourceManager.GetString("ThankYouForPurchasingAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing DilKeRishte PLANNAME plan..
        /// </summary>
        public static string ThankYouForPurchasingPlan {
            get {
                return ResourceManager.GetString("ThankYouForPurchasingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for register with us. An activation link sent to your email address for your email verification..
        /// </summary>
        public static string ThankYouForRegister {
            get {
                return ResourceManager.GetString("ThankYouForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for saving identity proof information!!.
        /// </summary>
        public static string ThankYouForSavingIdentityProofInformation {
            get {
                return ResourceManager.GetString("ThankYouForSavingIdentityProofInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for uploading Identities .
        /// </summary>
        public static string ThankYouForUploadingGovtId {
            get {
                return ResourceManager.GetString("ThankYouForUploadingGovtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for verify your email address. Your profile under screening it will be live in 12 working hours..
        /// </summary>
        public static string ThankYouForVerifyYourEmailAddress {
            get {
                return ResourceManager.GetString("ThankYouForVerifyYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your enquiry. It has been sent succesfully..
        /// </summary>
        public static string Thankyouforyourenquiry {
            get {
                return ResourceManager.GetString("Thankyouforyourenquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your enquiry. It has been sent successfully..
        /// </summary>
        public static string ThankYouForYourEnquirySuccessfully {
            get {
                return ResourceManager.GetString("ThankYouForYourEnquirySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you from dil ke rishte..
        /// </summary>
        public static string ThankYoufromDilKeRishte {
            get {
                return ResourceManager.GetString("ThankYoufromDilKeRishte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Succesfully applied for.
        /// </summary>
        public static string ThankyouSuccesfullyAppliedFor {
            get {
                return ResourceManager.GetString("ThankyouSuccesfullyAppliedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Succesfully uploaded..
        /// </summary>
        public static string ThankyouSuccesfullyUploaded {
            get {
                return ResourceManager.GetString("ThankyouSuccesfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Email Address or Password was incorrect..
        /// </summary>
        public static string TheEmailAddressPasswordEnteredInvalid {
            get {
                return ResourceManager.GetString("TheEmailAddressPasswordEnteredInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This promo code is invalid or has expired..
        /// </summary>
        public static string ThisPromoCodeIsInvalidOrHasExpired {
            get {
                return ResourceManager.GetString("ThisPromoCodeIsInvalidOrHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully..
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName has requested for data..
        /// </summary>
        public static string UserNameHasRequestedForData {
            get {
                return ResourceManager.GetString("UserNameHasRequestedForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName has sent you invitation.
        /// </summary>
        public static string UserNameHasSentYouInvitation {
            get {
                return ResourceManager.GetString("UserNameHasSentYouInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName has visited your profile..
        /// </summary>
        public static string UserNameHasVisitedYourProfile {
            get {
                return ResourceManager.GetString("UserNameHasVisitedYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Code.
        /// </summary>
        public static string ValidCode {
            get {
                return ResourceManager.GetString("ValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video deleted successfully..
        /// </summary>
        public static string VideoDeletedSuccessfully {
            get {
                return ResourceManager.GetString("VideoDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Uploaded Successfully..
        /// </summary>
        public static string VideoUploadedSuccessfully {
            get {
                return ResourceManager.GetString("VideoUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible only on invitation send accecpted..
        /// </summary>
        public static string VisibleOnlyOnInvitationSendAccecpted {
            get {
                return ResourceManager.GetString("VisibleOnlyOnInvitationSendAccecpted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to Premium Members.
        /// </summary>
        public static string VisibleToPremiumMembers {
            get {
                return ResourceManager.GetString("VisibleToPremiumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already Free Member..
        /// </summary>
        public static string YouAlreadyFreeMember {
            get {
                return ResourceManager.GetString("YouAlreadyFreeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t upload more than 10 images..
        /// </summary>
        public static string YouCantUploadMoreThan10Images {
            get {
                return ResourceManager.GetString("YouCantUploadMoreThan10Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have accepted invitation of Username.
        /// </summary>
        public static string YouHaveAcceptedInvitationUserName {
            get {
                return ResourceManager.GetString("YouHaveAcceptedInvitationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already verified your email id..
        /// </summary>
        public static string YouHaveAlreadyVerifiedYourEmailId {
            get {
                return ResourceManager.GetString("YouHaveAlreadyVerifiedYourEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the invitation of UserName..
        /// </summary>
        public static string YouHaveCancelledTheInvitationofUserName {
            get {
                return ResourceManager.GetString("YouHaveCancelledTheInvitationofUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have declined invitation of UserName..
        /// </summary>
        public static string YouHaveDeclinedInvitationofUserName {
            get {
                return ResourceManager.GetString("YouHaveDeclinedInvitationofUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed UserName from connected list..
        /// </summary>
        public static string YouHaveRemovedUserNameFromConnectedList {
            get {
                return ResourceManager.GetString("YouHaveRemovedUserNameFromConnectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent invitation to Username..
        /// </summary>
        public static string YouHaveSentInvitationToProfileName {
            get {
                return ResourceManager.GetString("YouHaveSentInvitationToProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent sms to UserName..
        /// </summary>
        public static string YouHaveSentSMSToUserName {
            get {
                return ResourceManager.GetString("YouHaveSentSMSToUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered with us..
        /// </summary>
        public static string YouHaveSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("YouHaveSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upgrade your membership to connect with premium member on  chat &amp; video call..
        /// </summary>
        public static string YouNeedToUpgradeMembership {
            get {
                return ResourceManager.GetString("YouNeedToUpgradeMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is under verification or you can contact our support.
        /// </summary>
        public static string YourAccountUnderVerificationYouCanContactOurSupport {
            get {
                return ResourceManager.GetString("YourAccountUnderVerificationYouCanContactOurSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dil Ke Rishte profile is under screening..
        /// </summary>
        public static string YourDilKeRishteProfileisUnderScreening {
            get {
                return ResourceManager.GetString("YourDilKeRishteProfileisUnderScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address verified.
        /// </summary>
        public static string YourEmailAddressVerified {
            get {
                return ResourceManager.GetString("YourEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is saved successfully..
        /// </summary>
        public static string YourFeedbackIsSavedSuccessfully {
            get {
                return ResourceManager.GetString("YourFeedbackIsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document(s) under approval..
        /// </summary>
        public static string YourIdIsUnderApproval {
            get {
                return ResourceManager.GetString("YourIdIsUnderApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mobile no is verified successfully..
        /// </summary>
        public static string YourMobileNoIsVerifiedSuccessfully {
            get {
                return ResourceManager.GetString("YourMobileNoIsVerifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has been sent to your mobile no. Please enter it to verify your mobile no..
        /// </summary>
        public static string YourOTPHasBeenSentYourMobileNo {
            get {
                return ResourceManager.GetString("YourOTPHasBeenSentYourMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP has been sent to your mobile no. Please enter it to verify your mobile no.Today send OTP remaining limit is .
        /// </summary>
        public static string YourOTPHasBeenSentYourMobileNoWithLimit {
            get {
                return ResourceManager.GetString("YourOTPHasBeenSentYourMobileNoWithLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for callback saved successfully..
        /// </summary>
        public static string YourRequestForCallbackSavedSuccessfully {
            get {
                return ResourceManager.GetString("YourRequestForCallbackSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification identity has been rejected. Please upload your indentity.
        /// </summary>
        public static string YourVerificationIdentityHasBeenRejected {
            get {
                return ResourceManager.GetString("YourVerificationIdentityHasBeenRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification identity still under approval..
        /// </summary>
        public static string YourVerificationIdentityStillUnderApproval {
            get {
                return ResourceManager.GetString("YourVerificationIdentityStillUnderApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would have limited access to your account till your ID is verified by DKR team which may take upto 9 business hours.
        /// </summary>
        public static string YouWouldHaveLimitedAccess {
            get {
                return ResourceManager.GetString("YouWouldHaveLimitedAccess", resourceCulture);
            }
        }
    }
}
